import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    alias(libs.plugins.android.library)
}

// LC-Build-TODO: addFrameworkJar() doesn't work, what???
def frameworkJar = new File("$rootDir/prebuilts/libs", "framework-16.jar")
tasks.withType(JavaCompile).configureEach {
    classpath = files(frameworkJar, classpath ?: project.files())
}
tasks.withType(KotlinCompile).configureEach {
    libraries.from(files(frameworkJar))
}

android {
    namespace = "com.android.app.animation"
    testNamespace = "com.android.app.animation.tests"
    defaultConfig {
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    sourceSets {
        main {
            java.srcDirs = ['src']
            kotlin.directories.add('src')
            res.srcDirs = ['res']
            manifest.srcFile 'AndroidManifest.xml'
        }
        androidTest {
            java.srcDirs = ["tests/src", "tests/robolectric/src"]
            manifest.srcFile 'tests/AndroidManifest.xml'
        }
    }

    lint {
        abortOnError false
    }
    tasks.lint.enabled = false
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
    }
}

addFrameworkJar('framework-16.jar')

dependencies {
    implementation libs.kotlin.stdlib.jdk7
    implementation libs.androidx.core.animation
    implementation libs.androidx.core.ktx
//    androidTestImplementation libs.robolectric
//    androidTestImplementation "androidx.test.ext:junit:1.1.3"
//    androidTestImplementation "androidx.test:rules:1.4.0"
}
apply plugin: 'kotlin-android'
