plugins {
    alias(libs.plugins.android.library)
}

// LC-Build-TODO: addFrameworkJar() now handles classpath globally via projectsEvaluated

android {
    namespace = "com.android.app.msdl"
    testNamespace = "com.android.app.msdl.tests"
    defaultConfig {
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    sourceSets {
        main {
            java.srcDirs = ['src']
            kotlin.srcDirs = ['src']
            res.srcDirs = ['res']
            manifest.srcFile 'AndroidManifest.xml'
        }
        androidTest {
            java.srcDirs = ["tests"]
            manifest.srcFile "tests/AndroidManifest.xml"
        }
    }
    lint {
        abortOnError false
    }
}

addFrameworkJar('framework-16.jar')

dependencies {
    implementation libs.androidx.core.ktx
}
