import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

// LC-Build-TODO: addFrameworkJar() doesn't work, what???
def frameworkJar = new File("$rootDir/prebuilts/libs", "framework-16.jar")
tasks.withType(JavaCompile).configureEach {
    classpath = files(frameworkJar, classpath)
}
tasks.withType(KotlinCompile).configureEach {
    libraries.from(files(frameworkJar))
}

android {
    namespace = "com.google.android.msdl"
    testNamespace = "com.google.android.msdl.tests"
    defaultConfig {
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    sourceSets {
        main {
            java.srcDirs = ['src']
            manifest.srcFile 'AndroidManifest.xml'
        }
//        androidTest {
//            java.srcDirs = ["tests/src"]
//            manifest.srcFile 'tests/AndroidManifest.xml'
//        }
    }
    lint {
        abortOnError false
    }
    tasks.lint.enabled = false
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
    }
}

addFrameworkJar('framework-16.jar')

dependencies {
    implementation libs.kotlin.stdlib.jdk7
    implementation libs.androidx.core.animation
    implementation libs.androidx.core.ktx
}
