import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    alias(libs.plugins.android.library)
}

// Lawnchair-TODO-Postmerge: AOSP now uses kts build scripts for this

// LC-Build-TODO: addFrameworkJar() doesn't work, what???
def frameworkJar = new File("$rootDir/prebuilts/libs", "framework-16.jar")
tasks.withType(JavaCompile).configureEach {
    classpath = files(frameworkJar, classpath)
}
tasks.withType(KotlinCompile).configureEach {
    libraries.from(files(frameworkJar))
}

android {
    namespace "com.android.launcher3.icons"
    sourceSets {
        main {
            java.srcDirs = ['src', 'src_full_lib']
            res.srcDirs = ['res']
        }
    }
}

addFrameworkJar('framework-16.jar')

dependencies {
    implementation libs.androidx.palette.ktx
    compileOnly projects.flags
}
